### PR TITLE
Ohno I made a terrible mistake

### PR DESCRIPTION
**Pull request by 4D4850**
Fixed the terrible mistake

### CODE REVIEW

**Comment by EarthBounded** [comment]
i am sorry, but i think your merge caused some, to say the very least, problems with the src, i run a beta for this mod and i found the latest src, which was from your merge, failed to compile, i compile every update, so i know there is something wrong with your src, log info is below

please fix this, The_Roman_Coder

C:\Users\*****\Downloads\The-Powder-Toy>meson build-debug
The Meson build system
Version: 0.60.0
Source dir: C:\Users\*****\Downloads\The-Powder-Toy
Build dir: C:\Users\*****\Downloads\The-Powder-Toy\build-debug
Build type: native build
Project name: the-powder-toy
Project version: the.cake.is.a.lie
Activating VS 17.0.0 RC3
C compiler for the host machine: cl (msvc 19.30.30705 "Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30705 for x64")
C linker for the host machine: link link 14.30.30705.0
C++ compiler for the host machine: cl (msvc 19.30.30705 "Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30705 for x64")
C++ linker for the host machine: link link 14.30.30705.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program C:\Users\natha\AppData\Local\Programs\Python\Python310\python found: YES (C:\Users\natha\AppData\Local\Programs\Python\Python310\python.exe)
WARNING: Broken python installation detected. Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Broken python installation detected. Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Downloading tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911 source from https://github.com/The-Powder-Toy/tpt-libs/releases/download/v20210712201911/tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911.zip
Download size: 1975882
Downloading: ..........

Executing subproject tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911

tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Project name: tpt-libs-prebuilt-win64-dynamic
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Project version: undefined
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| C compiler for the host machine: cl (msvc 19.30.30705 "Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30705 for x64")
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| C linker for the host machine: link link 14.30.30705.0
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| C++ compiler for the host machine: cl (msvc 19.30.30705 "Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30705 for x64")
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| C++ linker for the host machine: link link 14.30.30705.0
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library z found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library SDL2 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library fftw3f found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library curl found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library lua5.2 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library lua5.1 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library luajit21 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library shell32 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library wsock32 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library user32 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library Advapi32 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library ws2_32 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library Wldap32 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library crypt32 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library winmm found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Library gdi32 found: YES
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Build targets in project: 0
tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911| Subproject tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911 finished.

Run-time dependency threads found: YES
Message: SSE explicitly configured but unavailable in msvc targeting 64-bit machines
Configuring Config.h using configuration
Configuring ElementNumbers.h using configuration
Configuring ToolNumbers.h using configuration
Windows resource compiler: Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Build targets in project: 2

the-powder-toy the.cake.is.a.lie

  Subprojects
    tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911: YES

Found ninja-1.10.2.git.kitware.jobserver-1 at C:\Users\natha\AppData\Local\Programs\Python\Python310\Scripts\ninja.EXE
WARNING: msvc does not support C++11; attempting best effort; setting the standard to C++14

C:\Users\*****\Downloads\The-Powder-Toy>cd build-debug

C:\Users\natha\Downloads\The-Powder-Toy\build-debug>ninja
[4/372] Precompiling header powder.exe.p/meson_pch-cpp.cpp
FAILED: powder.exe.p/pch_cpp.pch
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "-I..\pch" "/nologo" "/showIncludes" "/utf-8" "/W2" "/EHsc" "/std:c++14" "/permissive-" "/Od" "/Zi" "/Ycpch_cpp.h" "/Fppowder.exe.p\pch_cpp.pch" "/Fopowder.exe.p\pch_cpp.obj" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/EHsc" "/std:c++14" "/permissive-" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" "/c" powder.exe.p/meson_pch-cpp.cpp
CreateProcess failed: The system cannot find the file specified.
[5/372] Compiling C object powder.exe.p/src_lua_LuaCompat.c.obj
FAILED: powder.exe.p/src_lua_LuaCompat.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_lua_LuaCompat.c.obj "/c" ../src/lua/LuaCompat.c
CreateProcess failed: The system cannot find the file specified.
[6/372] Compiling C object powder.exe.p/src_bzip2_blocksort.c.obj
FAILED: powder.exe.p/src_bzip2_blocksort.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_bzip2_blocksort.c.obj "/c" ../src/bzip2/blocksort.c
CreateProcess failed: The system cannot find the file specified.
[7/372] Compiling C object powder.exe.p/src_bzip2_crctable.c.obj
FAILED: powder.exe.p/src_bzip2_crctable.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_bzip2_crctable.c.obj "/c" ../src/bzip2/crctable.c
CreateProcess failed: The system cannot find the file specified.
[8/372] Compiling C object powder.exe.p/src_bzip2_decompress.c.obj
FAILED: powder.exe.p/src_bzip2_decompress.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_bzip2_decompress.c.obj "/c" ../src/bzip2/decompress.c
CreateProcess failed: The system cannot find the file specified.
[9/372] Compiling C object powder.exe.p/src_bzip2_randtable.c.obj
FAILED: powder.exe.p/src_bzip2_randtable.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_bzip2_randtable.c.obj "/c" ../src/bzip2/randtable.c
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

C:\Users\*****\Downloads\The-Powder-Toy\build-debug>

**Comment by 4D4850** [comment]
That's odd. I only changed the README, so I can't imagine what it could be. Just briefly looking over the logs, I noticed meson saying stuff about a broken python install, so it might be related to that. Alternatively, if you mean the most recent PR that was accepted, try using an older version, or get binaries from the workflows tab (if that is available).

**Comment by EarthBounded** [comment]
it was with the version that spike pulled on merge [#4 ](https://github.com/SpikeViper/The-Powder-Toy/pull/4)

**Comment by EarthBounded** [comment]
im sorry for  how long it took to comment this, im a gamer and i just turned 13

**Comment by EarthBounded** [comment]
look at each individual error after i run the "ninja" command, each error will be separate

[4/372] Precompiling header powder.exe.p/meson_pch-cpp.cpp
FAILED: powder.exe.p/pch_cpp.pch
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "-I..\pch" "/nologo" "/showIncludes" "/utf-8" "/W2" "/EHsc" "/std:c++14" "/permissive-" "/Od" "/Zi" "/Ycpch_cpp.h" "/Fppowder.exe.p\pch_cpp.pch" "/Fopowder.exe.p\pch_cpp.obj" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/EHsc" "/std:c++14" "/permissive-" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" "/c" powder.exe.p/meson_pch-cpp.cpp
CreateProcess failed: The system cannot find the file specified.


[5/372] Compiling C object powder.exe.p/src_lua_LuaCompat.c.obj
FAILED: powder.exe.p/src_lua_LuaCompat.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_lua_LuaCompat.c.obj "/c" ../src/lua/LuaCompat.c
CreateProcess failed: The system cannot find the file specified.


[6/372] Compiling C object powder.exe.p/src_bzip2_blocksort.c.obj
FAILED: powder.exe.p/src_bzip2_blocksort.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_bzip2_blocksort.c.obj "/c" ../src/bzip2/blocksort.c
CreateProcess failed: The system cannot find the file specified.


[7/372] Compiling C object powder.exe.p/src_bzip2_crctable.c.obj
FAILED: powder.exe.p/src_bzip2_crctable.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_bzip2_crctable.c.obj "/c" ../src/bzip2/crctable.c
CreateProcess failed: The system cannot find the file specified.


[8/372] Compiling C object powder.exe.p/src_bzip2_decompress.c.obj
FAILED: powder.exe.p/src_bzip2_decompress.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_bzip2_decompress.c.obj "/c" ../src/bzip2/decompress.c
CreateProcess failed: The system cannot find the file specified.


[9/372] Compiling C object powder.exe.p/src_bzip2_randtable.c.obj
FAILED: powder.exe.p/src_bzip2_randtable.c.obj
"cl" "-Ipowder.exe.p" "-I." "-I.." "-Isrc" "-I..\src" "-Idata" "-I..\data" "-Iresources" "-I..\resources" "-Isrc\config\powder" "-I..\src\config\powder" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include" "-I..\subprojects\tpt-libs-prebuilt-x86_64-win-msvc-dynamic-v20210712201911\include\luajit-2.1" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "/GS" "-D_SCL_SECURE_NO_WARNINGS" "-D_WIN32_WINNT=0x0501" "/FS" "/FdC:\Users\natha\Downloads\The-Powder-Toy\build-debug\powder.pdb" /Fopowder.exe.p/src_bzip2_randtable.c.obj "/c" ../src/bzip2/randtable.c
CreateProcess failed: The system cannot find the file specified.

**Comment by EarthBounded** [comment]
also the broken python install is always there when compiling any tpt or tpt mod with meson

**Comment by EarthBounded** [comment]
it has been a while, i need you to fix these issues, i cannot get in contact with spike viper, so i need you to fix the problem, i can't do this on my own, i am very young and relatively new to compiling and coding

**Comment by EarthBounded** [comment]
if you do not fix this within the next month, i will fix your code myself and will explain the mistakes you made in the code

**Comment by SpikeViper** [comment]
Removed the reference entirely.

**Pull request closed without merging**
