### PR TITLE
Add poison and tweaks

### PR DESCRIPTION
**Pull request by 4D4850**
Poison is a cytotoxic sludge that will eat through meat. Tumor can now form from radioactive materials, but not from prot/neut/etc yet. 

Another issue is that the HUD is kinda broken.

### CODE REVIEW

**Comment by 4D4850** [comment]
Now, blood has a small immune system.

**Comment by 4D4850** [comment]
My next planned change is to add bacteria, because the immune system is kinda lonely, but I won't be able to code for a while because I have school. Also to fix the HUD, since I think I know how to fix it now.

**Comment by 4D4850** [comment]
HUD is still broken. I will try to find out how to fix it.

**Comment by 4D4850** [comment]
Ok, I've given up on fixing the HUD. That'll need to be fixed eventually.

**Comment by 4D4850** [comment]
I'm working on making bacteria, but it'll be a long while.

**Comment by 4D4850** [comment]
I've decided I'll work on bacteria in a different branch and had a different pull request for bacteria.

**Comment by Coca162** [comment]
@4D4850 Hey do you have discord? You seem like you are doing some great work so it would be great if you were there so it is easier to communicate with you!

The Discord - https://discord.gg/GPJHfwX9Uz

**Comment by 4D4850** [comment]
@Coca162 I do have discord, but not on my dev laptop. I might join the discord eventually, but not right now. I'll think about it. In the meantime, feel free to put pull requests on my main contribution repo if you think anything could be improved.

**Comment by SpikeViper** [comment]
I'd like to add viruses which  have a unique color, which immune cells make antibodies with the same color - which kill the viruses. But this is all great!

**Comment by SpikeViper** [comment]
AH I MEANT TO PULL

**Comment by SpikeViper** [comment]
There

**Comment by 4D4850** [comment]
Once I have a long break from school (Most likely thanksgiving time), I'll be able to work almost nonstop on bacteria code.

**Comment by 4D4850** [comment]
Regarding the bacteria code, I have most of it in place. All I have to do is add in mutations, test the code, fix the fatal bugs that are probably there, and open a pull request. In addition, making viruses that can be attacked by the immune system will be an easy bit of modification for viruses based on bacteria code, and only a major pain on the side of making it so all cells (Including blood, which already has the cancer metastasis stuff and so will be a huge pain to do) can be infected, and making antibodies effective enough to kill weak viruses, but not effective enough against strong viruses.

**Comment by lizardboy052** [comment]
how do i download the tumor and your other projects on powder toy

**Comment by lizardboy052** [comment]
i need help

**Comment by lizardboy052** [comment]
pleaseee

**Pull request merged**
