### PR TITLE
Add bone marrow

### PR DESCRIPTION
**Pull request by humannum14916**
Add MARW, which mostly acts like MEAT but will spawn a white blood cell if it hasn't seen one in a while.

Update: Add a custom icon for the Biology menu

### CODE REVIEW

**Comment by BeepBeep1234** [comment]
Bone marrow should also create normal blood

**Comment by humannum14916** [comment]
How would it know when to spawn more blood?

**Comment by BeepBeep1234** [comment]
Every minute if it hasn’t encoutered blood for 2 seconds it could spawn 1 pixel of blood?

**Comment by humannum14916** [comment]
That would be another two counters to keep track of, and I can't add any more. I'll try giving it a 1 in 5 chance to spawn blood if there is less than 4 blood around it.

**Comment by humannum14916** [comment]
MARW will now try to spawn blood if there isn't enough around it

**Comment by aarrbba123** [comment]
This looks cool,but I wonder what happens when only one side is exposed to the blood stream like this:Screenshot (19)
Would it generate more blood even though there is enough blood in the blood stream or its just going to do nothing?

**Comment by humannum14916** [comment]
When MARW tries to spawn BLD or WBLD, it can only spawn it in the 8 spaces around it, so only the MARW on the edge will actually create BLD.

**Comment by aarrbba123** [comment]
> It can only spawn it in the 8 spaces around it

I would probably assume that the sensing is similar to that, right?

**Comment by humannum14916** [comment]
Each pixel of MARW checks for BLD and WBLD in an 11x11 area around it, rather than the 3x3 area for spawning.

**Comment by aarrbba123** [comment]
> Each pixel of MARW checks for BLD and WBLD in an 11x11 area around it, rather than the 3x3 area for spawning.

Well that's good to know,sorry if I sound offensive to you.

**Comment by humannum14916** [comment]
You have not offended me in the slightest, I was actually really excited to see people interested in my contributions.

**Comment by humannum14916** [comment]
The Biology menu now has a custom icon! If you want to make a better one, see this guide (powdertoy.co.uk/Wiki/W/How_to_Add_Characters_and_Icons_to_the_Font.html) for how to edit the icon.

**Comment by aarrbba123** [comment]
So uhh,I may have accidentally merged your branch with mine so I can test that element myself and well...
look in my pr

**Comment by humannum14916** [comment]
I think the best way to fix it would be to undo the merge locally, but I'm not sure if that would work.

**Comment by aarrbba123** [comment]
I found out that commit history exists,thanks for your help

**Pull request merged**
